"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['setup-py2app.py']
DATA_FILES = ['--iconfile']
OPTIONS = {'argv_emulation': True,
 'iconfile': '/Users/Alvin/Workspace/Dropbox/Python/MLST/images/Main-icon.icns'}

setup(
    app=APP,
    name='MLSTAnalyser',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
