# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameterdlg.ui'
#
# Created: Thu Apr  3 14:23:36 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ParameterDlg(object):
    def setupUi(self, ParameterDlg):
        ParameterDlg.setObjectName(_fromUtf8("ParameterDlg"))
        ParameterDlg.resize(560, 455)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ParameterDlg.sizePolicy().hasHeightForWidth())
        ParameterDlg.setSizePolicy(sizePolicy)
        self.groupBox = QtGui.QGroupBox(ParameterDlg)
        self.groupBox.setGeometry(QtCore.QRect(10, 247, 541, 201))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 70, 428, 26))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_7.addWidget(self.label_3)
        self.uniprimerLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.uniprimerLineEdit.setObjectName(_fromUtf8("uniprimerLineEdit"))
        self.horizontalLayout_7.addWidget(self.uniprimerLineEdit)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.barcodelenSpinBox = QtGui.QSpinBox(self.layoutWidget)
        self.barcodelenSpinBox.setMinimum(1)
        self.barcodelenSpinBox.setProperty("value", 16)
        self.barcodelenSpinBox.setObjectName(_fromUtf8("barcodelenSpinBox"))
        self.horizontalLayout_7.addWidget(self.barcodelenSpinBox)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 100, 519, 26))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.mindepthSpinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.mindepthSpinBox.setMinimum(1)
        self.mindepthSpinBox.setProperty("value", 3)
        self.mindepthSpinBox.setObjectName(_fromUtf8("mindepthSpinBox"))
        self.horizontalLayout_8.addWidget(self.mindepthSpinBox)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_8.addWidget(self.label_6)
        self.maxdepthSpinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.maxdepthSpinBox.setMinimum(5)
        self.maxdepthSpinBox.setProperty("value", 10)
        self.maxdepthSpinBox.setObjectName(_fromUtf8("maxdepthSpinBox"))
        self.horizontalLayout_8.addWidget(self.maxdepthSpinBox)
        self.label_7 = QtGui.QLabel(self.layoutWidget1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_8.addWidget(self.label_7)
        self.flankinglengthSpinBox = QtGui.QSpinBox(self.layoutWidget1)
        self.flankinglengthSpinBox.setMaximum(20)
        self.flankinglengthSpinBox.setProperty("value", 5)
        self.flankinglengthSpinBox.setObjectName(_fromUtf8("flankinglengthSpinBox"))
        self.horizontalLayout_8.addWidget(self.flankinglengthSpinBox)
        self.layoutWidget2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 40, 483, 33))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.muscleLabel = QtGui.QLabel(self.layoutWidget2)
        self.muscleLabel.setObjectName(_fromUtf8("muscleLabel"))
        self.horizontalLayout_6.addWidget(self.muscleLabel)
        self.muscleLineEdit = QtGui.QLineEdit(self.layoutWidget2)
        self.muscleLineEdit.setObjectName(_fromUtf8("muscleLineEdit"))
        self.horizontalLayout_6.addWidget(self.muscleLineEdit)
        self.muscleButton = QtGui.QPushButton(self.layoutWidget2)
        self.muscleButton.setObjectName(_fromUtf8("muscleButton"))
        self.horizontalLayout_6.addWidget(self.muscleButton)
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.paddingEditLine = QtGui.QLineEdit(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paddingEditLine.sizePolicy().hasHeightForWidth())
        self.paddingEditLine.setSizePolicy(sizePolicy)
        self.paddingEditLine.setMaximumSize(QtCore.QSize(60, 16777215))
        self.paddingEditLine.setObjectName(_fromUtf8("paddingEditLine"))
        self.horizontalLayout_6.addWidget(self.paddingEditLine)
        self.layoutWidget3 = QtGui.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(11, 130, 445, 26))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_8 = QtGui.QLabel(self.layoutWidget3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_9.addWidget(self.label_8)
        self.matchscoreSpinBox = QtGui.QSpinBox(self.layoutWidget3)
        self.matchscoreSpinBox.setMinimum(0)
        self.matchscoreSpinBox.setMaximum(10)
        self.matchscoreSpinBox.setProperty("value", 2)
        self.matchscoreSpinBox.setObjectName(_fromUtf8("matchscoreSpinBox"))
        self.horizontalLayout_9.addWidget(self.matchscoreSpinBox)
        self.label_9 = QtGui.QLabel(self.layoutWidget3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_9.addWidget(self.label_9)
        self.mismatchscireSpinBox = QtGui.QSpinBox(self.layoutWidget3)
        self.mismatchscireSpinBox.setMinimum(-5)
        self.mismatchscireSpinBox.setMaximum(0)
        self.mismatchscireSpinBox.setProperty("value", -1)
        self.mismatchscireSpinBox.setObjectName(_fromUtf8("mismatchscireSpinBox"))
        self.horizontalLayout_9.addWidget(self.mismatchscireSpinBox)
        self.label_10 = QtGui.QLabel(self.layoutWidget3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_9.addWidget(self.label_10)
        self.gapscoreSpinBox = QtGui.QSpinBox(self.layoutWidget3)
        self.gapscoreSpinBox.setMinimum(-5)
        self.gapscoreSpinBox.setMaximum(0)
        self.gapscoreSpinBox.setProperty("value", -1)
        self.gapscoreSpinBox.setObjectName(_fromUtf8("gapscoreSpinBox"))
        self.horizontalLayout_9.addWidget(self.gapscoreSpinBox)
        self.layoutWidget4 = QtGui.QWidget(self.groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(11, 10, 517, 26))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.seqtypeLable = QtGui.QLabel(self.layoutWidget4)
        self.seqtypeLable.setObjectName(_fromUtf8("seqtypeLable"))
        self.horizontalLayout.addWidget(self.seqtypeLable)
        self.fastqRadioBtn = QtGui.QRadioButton(self.layoutWidget4)
        self.fastqRadioBtn.setChecked(True)
        self.fastqRadioBtn.setObjectName(_fromUtf8("fastqRadioBtn"))
        self.filetypeButtonGroup = QtGui.QButtonGroup(ParameterDlg)
        self.filetypeButtonGroup.setObjectName(_fromUtf8("filetypeButtonGroup"))
        self.filetypeButtonGroup.addButton(self.fastqRadioBtn)
        self.horizontalLayout.addWidget(self.fastqRadioBtn)
        self.fastaRadioBtn = QtGui.QRadioButton(self.layoutWidget4)
        self.fastaRadioBtn.setObjectName(_fromUtf8("fastaRadioBtn"))
        self.filetypeButtonGroup.addButton(self.fastaRadioBtn)
        self.horizontalLayout.addWidget(self.fastaRadioBtn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtGui.QLabel(self.layoutWidget4)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.phred33RadioBtn = QtGui.QRadioButton(self.layoutWidget4)
        self.phred33RadioBtn.setChecked(True)
        self.phred33RadioBtn.setObjectName(_fromUtf8("phred33RadioBtn"))
        self.scoretypeGroup = QtGui.QButtonGroup(ParameterDlg)
        self.scoretypeGroup.setObjectName(_fromUtf8("scoretypeGroup"))
        self.scoretypeGroup.addButton(self.phred33RadioBtn)
        self.horizontalLayout.addWidget(self.phred33RadioBtn)
        self.phred64RadioBtn = QtGui.QRadioButton(self.layoutWidget4)
        self.phred64RadioBtn.setObjectName(_fromUtf8("phred64RadioBtn"))
        self.scoretypeGroup.addButton(self.phred64RadioBtn)
        self.horizontalLayout.addWidget(self.phred64RadioBtn)
        self.layoutWidget5 = QtGui.QWidget(self.groupBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(11, 160, 281, 26))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_11 = QtGui.QLabel(self.layoutWidget5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_10.addWidget(self.label_11)
        self.maxmismatchSpinBox = QtGui.QSpinBox(self.layoutWidget5)
        self.maxmismatchSpinBox.setMaximum(5)
        self.maxmismatchSpinBox.setProperty("value", 3)
        self.maxmismatchSpinBox.setObjectName(_fromUtf8("maxmismatchSpinBox"))
        self.horizontalLayout_10.addWidget(self.maxmismatchSpinBox)
        self.label_12 = QtGui.QLabel(self.layoutWidget5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_10.addWidget(self.label_12)
        self.threadSpinBox = QtGui.QSpinBox(self.layoutWidget5)
        self.threadSpinBox.setMinimum(1)
        self.threadSpinBox.setMaximum(99)
        self.threadSpinBox.setProperty("value", 1)
        self.threadSpinBox.setObjectName(_fromUtf8("threadSpinBox"))
        self.horizontalLayout_10.addWidget(self.threadSpinBox)
        self.okayButton = QtGui.QPushButton(ParameterDlg)
        self.okayButton.setGeometry(QtCore.QRect(430, 10, 114, 32))
        self.okayButton.setObjectName(_fromUtf8("okayButton"))
        self.cancelButton = QtGui.QPushButton(ParameterDlg)
        self.cancelButton.setGeometry(QtCore.QRect(430, 40, 114, 32))
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.moreButton = QtGui.QPushButton(ParameterDlg)
        self.moreButton.setGeometry(QtCore.QRect(430, 90, 114, 32))
        self.moreButton.setCheckable(True)
        self.moreButton.setObjectName(_fromUtf8("moreButton"))
        self.line = QtGui.QFrame(ParameterDlg)
        self.line.setGeometry(QtCore.QRect(403, 10, 20, 221))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.layoutWidget6 = QtGui.QWidget(ParameterDlg)
        self.layoutWidget6.setGeometry(QtCore.QRect(11, 44, 383, 95))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.inputfileLabel = QtGui.QLabel(self.layoutWidget6)
        self.inputfileLabel.setObjectName(_fromUtf8("inputfileLabel"))
        self.verticalLayout.addWidget(self.inputfileLabel)
        self.addseqfileButton = QtGui.QPushButton(self.layoutWidget6)
        self.addseqfileButton.setObjectName(_fromUtf8("addseqfileButton"))
        self.verticalLayout.addWidget(self.addseqfileButton)
        self.removeseqfileButton = QtGui.QPushButton(self.layoutWidget6)
        self.removeseqfileButton.setObjectName(_fromUtf8("removeseqfileButton"))
        self.verticalLayout.addWidget(self.removeseqfileButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.seqfileListWidget = QtGui.QListWidget(self.layoutWidget6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seqfileListWidget.sizePolicy().hasHeightForWidth())
        self.seqfileListWidget.setSizePolicy(sizePolicy)
        self.seqfileListWidget.setMinimumSize(QtCore.QSize(0, 30))
        self.seqfileListWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.seqfileListWidget.setObjectName(_fromUtf8("seqfileListWidget"))
        self.horizontalLayout_5.addWidget(self.seqfileListWidget)
        self.layoutWidget7 = QtGui.QWidget(ParameterDlg)
        self.layoutWidget7.setGeometry(QtCore.QRect(12, 144, 381, 33))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.barcodefileLabel = QtGui.QLabel(self.layoutWidget7)
        self.barcodefileLabel.setObjectName(_fromUtf8("barcodefileLabel"))
        self.horizontalLayout_2.addWidget(self.barcodefileLabel)
        self.barcodefileLineEdit = QtGui.QLineEdit(self.layoutWidget7)
        self.barcodefileLineEdit.setObjectName(_fromUtf8("barcodefileLineEdit"))
        self.horizontalLayout_2.addWidget(self.barcodefileLineEdit)
        self.barcodefileButton = QtGui.QPushButton(self.layoutWidget7)
        self.barcodefileButton.setObjectName(_fromUtf8("barcodefileButton"))
        self.horizontalLayout_2.addWidget(self.barcodefileButton)
        self.layoutWidget8 = QtGui.QWidget(ParameterDlg)
        self.layoutWidget8.setGeometry(QtCore.QRect(12, 204, 381, 33))
        self.layoutWidget8.setObjectName(_fromUtf8("layoutWidget8"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.outfolderLabel = QtGui.QLabel(self.layoutWidget8)
        self.outfolderLabel.setObjectName(_fromUtf8("outfolderLabel"))
        self.horizontalLayout_4.addWidget(self.outfolderLabel)
        self.outfolderLineEdit = QtGui.QLineEdit(self.layoutWidget8)
        self.outfolderLineEdit.setObjectName(_fromUtf8("outfolderLineEdit"))
        self.horizontalLayout_4.addWidget(self.outfolderLineEdit)
        self.outfolderButton = QtGui.QPushButton(self.layoutWidget8)
        self.outfolderButton.setObjectName(_fromUtf8("outfolderButton"))
        self.horizontalLayout_4.addWidget(self.outfolderButton)
        self.layoutWidget9 = QtGui.QWidget(ParameterDlg)
        self.layoutWidget9.setGeometry(QtCore.QRect(12, 174, 381, 33))
        self.layoutWidget9.setObjectName(_fromUtf8("layoutWidget9"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.primerfileLabel = QtGui.QLabel(self.layoutWidget9)
        self.primerfileLabel.setObjectName(_fromUtf8("primerfileLabel"))
        self.horizontalLayout_3.addWidget(self.primerfileLabel)
        self.primerfileLineEdit = QtGui.QLineEdit(self.layoutWidget9)
        self.primerfileLineEdit.setObjectName(_fromUtf8("primerfileLineEdit"))
        self.horizontalLayout_3.addWidget(self.primerfileLineEdit)
        self.primerfileButton = QtGui.QPushButton(self.layoutWidget9)
        self.primerfileButton.setObjectName(_fromUtf8("primerfileButton"))
        self.horizontalLayout_3.addWidget(self.primerfileButton)
        self.layoutWidget10 = QtGui.QWidget(ParameterDlg)
        self.layoutWidget10.setGeometry(QtCore.QRect(17, 12, 240, 23))
        self.layoutWidget10.setObjectName(_fromUtf8("layoutWidget10"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_13 = QtGui.QLabel(self.layoutWidget10)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_11.addWidget(self.label_13)
        self.projnameLineEdit = QtGui.QLineEdit(self.layoutWidget10)
        self.projnameLineEdit.setObjectName(_fromUtf8("projnameLineEdit"))
        self.horizontalLayout_11.addWidget(self.projnameLineEdit)
        self.label_3.setBuddy(self.uniprimerLineEdit)
        self.label_4.setBuddy(self.barcodelenSpinBox)
        self.label_5.setBuddy(self.mindepthSpinBox)
        self.label_6.setBuddy(self.maxdepthSpinBox)
        self.label_7.setBuddy(self.flankinglengthSpinBox)
        self.muscleLabel.setBuddy(self.muscleLineEdit)
        self.label_2.setBuddy(self.paddingEditLine)
        self.label_8.setBuddy(self.matchscoreSpinBox)
        self.label_9.setBuddy(self.mismatchscireSpinBox)
        self.label_10.setBuddy(self.gapscoreSpinBox)
        self.seqtypeLable.setBuddy(self.fastqRadioBtn)
        self.label.setBuddy(self.phred33RadioBtn)
        self.label_11.setBuddy(self.maxmismatchSpinBox)
        self.label_12.setBuddy(self.threadSpinBox)
        self.inputfileLabel.setBuddy(self.addseqfileButton)
        self.barcodefileLabel.setBuddy(self.barcodefileLineEdit)
        self.outfolderLabel.setBuddy(self.outfolderLineEdit)
        self.primerfileLabel.setBuddy(self.primerfileLineEdit)
        self.label_13.setBuddy(self.projnameLineEdit)

        self.retranslateUi(ParameterDlg)
        QtCore.QObject.connect(self.cancelButton, QtCore.SIGNAL(_fromUtf8("clicked()")), ParameterDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(ParameterDlg)
        ParameterDlg.setTabOrder(self.projnameLineEdit, self.addseqfileButton)
        ParameterDlg.setTabOrder(self.addseqfileButton, self.removeseqfileButton)
        ParameterDlg.setTabOrder(self.removeseqfileButton, self.barcodefileButton)
        ParameterDlg.setTabOrder(self.barcodefileButton, self.primerfileButton)
        ParameterDlg.setTabOrder(self.primerfileButton, self.outfolderButton)
        ParameterDlg.setTabOrder(self.outfolderButton, self.okayButton)
        ParameterDlg.setTabOrder(self.okayButton, self.cancelButton)
        ParameterDlg.setTabOrder(self.cancelButton, self.moreButton)
        ParameterDlg.setTabOrder(self.moreButton, self.fastqRadioBtn)
        ParameterDlg.setTabOrder(self.fastqRadioBtn, self.fastaRadioBtn)
        ParameterDlg.setTabOrder(self.fastaRadioBtn, self.phred33RadioBtn)
        ParameterDlg.setTabOrder(self.phred33RadioBtn, self.phred64RadioBtn)
        ParameterDlg.setTabOrder(self.phred64RadioBtn, self.muscleLineEdit)
        ParameterDlg.setTabOrder(self.muscleLineEdit, self.muscleButton)
        ParameterDlg.setTabOrder(self.muscleButton, self.paddingEditLine)
        ParameterDlg.setTabOrder(self.paddingEditLine, self.uniprimerLineEdit)
        ParameterDlg.setTabOrder(self.uniprimerLineEdit, self.barcodelenSpinBox)
        ParameterDlg.setTabOrder(self.barcodelenSpinBox, self.mindepthSpinBox)
        ParameterDlg.setTabOrder(self.mindepthSpinBox, self.maxdepthSpinBox)
        ParameterDlg.setTabOrder(self.maxdepthSpinBox, self.flankinglengthSpinBox)
        ParameterDlg.setTabOrder(self.flankinglengthSpinBox, self.matchscoreSpinBox)
        ParameterDlg.setTabOrder(self.matchscoreSpinBox, self.mismatchscireSpinBox)
        ParameterDlg.setTabOrder(self.mismatchscireSpinBox, self.gapscoreSpinBox)
        ParameterDlg.setTabOrder(self.gapscoreSpinBox, self.maxmismatchSpinBox)
        ParameterDlg.setTabOrder(self.maxmismatchSpinBox, self.threadSpinBox)
        ParameterDlg.setTabOrder(self.threadSpinBox, self.seqfileListWidget)
        ParameterDlg.setTabOrder(self.seqfileListWidget, self.barcodefileLineEdit)
        ParameterDlg.setTabOrder(self.barcodefileLineEdit, self.primerfileLineEdit)
        ParameterDlg.setTabOrder(self.primerfileLineEdit, self.outfolderLineEdit)

    def retranslateUi(self, ParameterDlg):
        ParameterDlg.setWindowTitle(_translate("ParameterDlg", "Project Settings", None))
        self.label_3.setText(_translate("ParameterDlg", "Universal Primer:", None))
        self.label_4.setText(_translate("ParameterDlg", "Barcode Length:", None))
        self.label_5.setText(_translate("ParameterDlg", "Min Read Depth:", None))
        self.label_6.setText(_translate("ParameterDlg", "Max Read Depth:", None))
        self.label_7.setText(_translate("ParameterDlg", "Flanking Length:", None))
        self.muscleLabel.setText(_translate("ParameterDlg", "MUSCLE:", None))
        self.muscleButton.setText(_translate("ParameterDlg", "Select", None))
        self.label_2.setText(_translate("ParameterDlg", "Padding Sequence:", None))
        self.label_8.setText(_translate("ParameterDlg", "Match Score:", None))
        self.label_9.setText(_translate("ParameterDlg", "Mismatch Score:", None))
        self.label_10.setText(_translate("ParameterDlg", "Gap Score:", None))
        self.seqtypeLable.setText(_translate("ParameterDlg", "File Format:", None))
        self.fastqRadioBtn.setText(_translate("ParameterDlg", "FASTQ", None))
        self.fastaRadioBtn.setText(_translate("ParameterDlg", "FASTA", None))
        self.label.setText(_translate("ParameterDlg", "Score Type:", None))
        self.phred33RadioBtn.setText(_translate("ParameterDlg", "phred33", None))
        self.phred64RadioBtn.setText(_translate("ParameterDlg", "phred64", None))
        self.label_11.setText(_translate("ParameterDlg", "Max Mismatch:", None))
        self.label_12.setText(_translate("ParameterDlg", "Threads", None))
        self.okayButton.setText(_translate("ParameterDlg", "OK", None))
        self.cancelButton.setText(_translate("ParameterDlg", "Cancel", None))
        self.moreButton.setText(_translate("ParameterDlg", "Advanced >>", None))
        self.inputfileLabel.setText(_translate("ParameterDlg", "Sequencing Files:", None))
        self.addseqfileButton.setText(_translate("ParameterDlg", "Add File", None))
        self.removeseqfileButton.setText(_translate("ParameterDlg", "Remove File", None))
        self.barcodefileLabel.setText(_translate("ParameterDlg", "Barcode File:", None))
        self.barcodefileButton.setText(_translate("ParameterDlg", "Select", None))
        self.outfolderLabel.setText(_translate("ParameterDlg", "Output Folder:", None))
        self.outfolderButton.setText(_translate("ParameterDlg", "Select", None))
        self.primerfileLabel.setText(_translate("ParameterDlg", "Primer File:", None))
        self.primerfileButton.setText(_translate("ParameterDlg", "Select", None))
        self.label_13.setText(_translate("ParameterDlg", "Project Name:", None))

