# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameterdlg.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ParameterDlg(object):
    def setupUi(self, ParameterDlg):
        ParameterDlg.setObjectName("ParameterDlg")
        ParameterDlg.resize(560, 455)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ParameterDlg.sizePolicy().hasHeightForWidth())
        ParameterDlg.setSizePolicy(sizePolicy)
        self.groupBox = QtWidgets.QGroupBox(ParameterDlg)
        self.groupBox.setGeometry(QtCore.QRect(10, 247, 541, 201))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 70, 428, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.uniprimerLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.uniprimerLineEdit.setObjectName("uniprimerLineEdit")
        self.horizontalLayout_7.addWidget(self.uniprimerLineEdit)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.barcodelenSpinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.barcodelenSpinBox.setMinimum(1)
        self.barcodelenSpinBox.setProperty("value", 16)
        self.barcodelenSpinBox.setObjectName("barcodelenSpinBox")
        self.horizontalLayout_7.addWidget(self.barcodelenSpinBox)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 100, 519, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.mindepthSpinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.mindepthSpinBox.setMinimum(1)
        self.mindepthSpinBox.setProperty("value", 3)
        self.mindepthSpinBox.setObjectName("mindepthSpinBox")
        self.horizontalLayout_8.addWidget(self.mindepthSpinBox)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.maxdepthSpinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.maxdepthSpinBox.setMinimum(5)
        self.maxdepthSpinBox.setProperty("value", 10)
        self.maxdepthSpinBox.setObjectName("maxdepthSpinBox")
        self.horizontalLayout_8.addWidget(self.maxdepthSpinBox)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.flankinglengthSpinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.flankinglengthSpinBox.setMaximum(20)
        self.flankinglengthSpinBox.setProperty("value", 5)
        self.flankinglengthSpinBox.setObjectName("flankinglengthSpinBox")
        self.horizontalLayout_8.addWidget(self.flankinglengthSpinBox)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 40, 483, 33))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.muscleLabel = QtWidgets.QLabel(self.layoutWidget2)
        self.muscleLabel.setObjectName("muscleLabel")
        self.horizontalLayout_6.addWidget(self.muscleLabel)
        self.muscleLineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.muscleLineEdit.setObjectName("muscleLineEdit")
        self.horizontalLayout_6.addWidget(self.muscleLineEdit)
        self.muscleButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.muscleButton.setObjectName("muscleButton")
        self.horizontalLayout_6.addWidget(self.muscleButton)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.paddingEditLine = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paddingEditLine.sizePolicy().hasHeightForWidth())
        self.paddingEditLine.setSizePolicy(sizePolicy)
        self.paddingEditLine.setMaximumSize(QtCore.QSize(60, 16777215))
        self.paddingEditLine.setObjectName("paddingEditLine")
        self.horizontalLayout_6.addWidget(self.paddingEditLine)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(11, 130, 445, 26))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        self.matchscoreSpinBox = QtWidgets.QSpinBox(self.layoutWidget3)
        self.matchscoreSpinBox.setMinimum(0)
        self.matchscoreSpinBox.setMaximum(10)
        self.matchscoreSpinBox.setProperty("value", 2)
        self.matchscoreSpinBox.setObjectName("matchscoreSpinBox")
        self.horizontalLayout_9.addWidget(self.matchscoreSpinBox)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.mismatchscireSpinBox = QtWidgets.QSpinBox(self.layoutWidget3)
        self.mismatchscireSpinBox.setMinimum(-5)
        self.mismatchscireSpinBox.setMaximum(0)
        self.mismatchscireSpinBox.setProperty("value", -1)
        self.mismatchscireSpinBox.setObjectName("mismatchscireSpinBox")
        self.horizontalLayout_9.addWidget(self.mismatchscireSpinBox)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.gapscoreSpinBox = QtWidgets.QSpinBox(self.layoutWidget3)
        self.gapscoreSpinBox.setMinimum(-5)
        self.gapscoreSpinBox.setMaximum(0)
        self.gapscoreSpinBox.setProperty("value", -1)
        self.gapscoreSpinBox.setObjectName("gapscoreSpinBox")
        self.horizontalLayout_9.addWidget(self.gapscoreSpinBox)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(11, 10, 517, 26))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.seqtypeLable = QtWidgets.QLabel(self.layoutWidget4)
        self.seqtypeLable.setObjectName("seqtypeLable")
        self.horizontalLayout.addWidget(self.seqtypeLable)
        self.fastqRadioBtn = QtWidgets.QRadioButton(self.layoutWidget4)
        self.fastqRadioBtn.setChecked(True)
        self.fastqRadioBtn.setObjectName("fastqRadioBtn")
        self.filetypeButtonGroup = QtWidgets.QButtonGroup(ParameterDlg)
        self.filetypeButtonGroup.setObjectName("filetypeButtonGroup")
        self.filetypeButtonGroup.addButton(self.fastqRadioBtn)
        self.horizontalLayout.addWidget(self.fastqRadioBtn)
        self.fastaRadioBtn = QtWidgets.QRadioButton(self.layoutWidget4)
        self.fastaRadioBtn.setObjectName("fastaRadioBtn")
        self.filetypeButtonGroup.addButton(self.fastaRadioBtn)
        self.horizontalLayout.addWidget(self.fastaRadioBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.layoutWidget4)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.phred33RadioBtn = QtWidgets.QRadioButton(self.layoutWidget4)
        self.phred33RadioBtn.setChecked(True)
        self.phred33RadioBtn.setObjectName("phred33RadioBtn")
        self.scoretypeGroup = QtWidgets.QButtonGroup(ParameterDlg)
        self.scoretypeGroup.setObjectName("scoretypeGroup")
        self.scoretypeGroup.addButton(self.phred33RadioBtn)
        self.horizontalLayout.addWidget(self.phred33RadioBtn)
        self.phred64RadioBtn = QtWidgets.QRadioButton(self.layoutWidget4)
        self.phred64RadioBtn.setObjectName("phred64RadioBtn")
        self.scoretypeGroup.addButton(self.phred64RadioBtn)
        self.horizontalLayout.addWidget(self.phred64RadioBtn)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(11, 160, 281, 26))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_10.addWidget(self.label_11)
        self.maxmismatchSpinBox = QtWidgets.QSpinBox(self.layoutWidget5)
        self.maxmismatchSpinBox.setMaximum(5)
        self.maxmismatchSpinBox.setProperty("value", 3)
        self.maxmismatchSpinBox.setObjectName("maxmismatchSpinBox")
        self.horizontalLayout_10.addWidget(self.maxmismatchSpinBox)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.threadSpinBox = QtWidgets.QSpinBox(self.layoutWidget5)
        self.threadSpinBox.setMinimum(1)
        self.threadSpinBox.setMaximum(99)
        self.threadSpinBox.setProperty("value", 1)
        self.threadSpinBox.setObjectName("threadSpinBox")
        self.horizontalLayout_10.addWidget(self.threadSpinBox)
        self.okayButton = QtWidgets.QPushButton(ParameterDlg)
        self.okayButton.setGeometry(QtCore.QRect(430, 10, 114, 32))
        self.okayButton.setObjectName("okayButton")
        self.cancelButton = QtWidgets.QPushButton(ParameterDlg)
        self.cancelButton.setGeometry(QtCore.QRect(430, 40, 114, 32))
        self.cancelButton.setObjectName("cancelButton")
        self.moreButton = QtWidgets.QPushButton(ParameterDlg)
        self.moreButton.setGeometry(QtCore.QRect(430, 90, 114, 32))
        self.moreButton.setCheckable(True)
        self.moreButton.setObjectName("moreButton")
        self.line = QtWidgets.QFrame(ParameterDlg)
        self.line.setGeometry(QtCore.QRect(403, 10, 20, 221))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget6 = QtWidgets.QWidget(ParameterDlg)
        self.layoutWidget6.setGeometry(QtCore.QRect(11, 44, 383, 95))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.inputfileLabel = QtWidgets.QLabel(self.layoutWidget6)
        self.inputfileLabel.setObjectName("inputfileLabel")
        self.verticalLayout.addWidget(self.inputfileLabel)
        self.addseqfileButton = QtWidgets.QPushButton(self.layoutWidget6)
        self.addseqfileButton.setObjectName("addseqfileButton")
        self.verticalLayout.addWidget(self.addseqfileButton)
        self.removeseqfileButton = QtWidgets.QPushButton(self.layoutWidget6)
        self.removeseqfileButton.setObjectName("removeseqfileButton")
        self.verticalLayout.addWidget(self.removeseqfileButton)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.seqfileListWidget = QtWidgets.QListWidget(self.layoutWidget6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seqfileListWidget.sizePolicy().hasHeightForWidth())
        self.seqfileListWidget.setSizePolicy(sizePolicy)
        self.seqfileListWidget.setMinimumSize(QtCore.QSize(0, 30))
        self.seqfileListWidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.seqfileListWidget.setObjectName("seqfileListWidget")
        self.horizontalLayout_5.addWidget(self.seqfileListWidget)
        self.layoutWidget7 = QtWidgets.QWidget(ParameterDlg)
        self.layoutWidget7.setGeometry(QtCore.QRect(12, 144, 381, 33))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.barcodefileLabel = QtWidgets.QLabel(self.layoutWidget7)
        self.barcodefileLabel.setObjectName("barcodefileLabel")
        self.horizontalLayout_2.addWidget(self.barcodefileLabel)
        self.barcodefileLineEdit = QtWidgets.QLineEdit(self.layoutWidget7)
        self.barcodefileLineEdit.setObjectName("barcodefileLineEdit")
        self.horizontalLayout_2.addWidget(self.barcodefileLineEdit)
        self.barcodefileButton = QtWidgets.QPushButton(self.layoutWidget7)
        self.barcodefileButton.setObjectName("barcodefileButton")
        self.horizontalLayout_2.addWidget(self.barcodefileButton)
        self.layoutWidget8 = QtWidgets.QWidget(ParameterDlg)
        self.layoutWidget8.setGeometry(QtCore.QRect(12, 204, 381, 33))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outfolderLabel = QtWidgets.QLabel(self.layoutWidget8)
        self.outfolderLabel.setObjectName("outfolderLabel")
        self.horizontalLayout_4.addWidget(self.outfolderLabel)
        self.outfolderLineEdit = QtWidgets.QLineEdit(self.layoutWidget8)
        self.outfolderLineEdit.setObjectName("outfolderLineEdit")
        self.horizontalLayout_4.addWidget(self.outfolderLineEdit)
        self.outfolderButton = QtWidgets.QPushButton(self.layoutWidget8)
        self.outfolderButton.setObjectName("outfolderButton")
        self.horizontalLayout_4.addWidget(self.outfolderButton)
        self.layoutWidget9 = QtWidgets.QWidget(ParameterDlg)
        self.layoutWidget9.setGeometry(QtCore.QRect(12, 174, 381, 33))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget9)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.primerfileLabel = QtWidgets.QLabel(self.layoutWidget9)
        self.primerfileLabel.setObjectName("primerfileLabel")
        self.horizontalLayout_3.addWidget(self.primerfileLabel)
        self.primerfileLineEdit = QtWidgets.QLineEdit(self.layoutWidget9)
        self.primerfileLineEdit.setObjectName("primerfileLineEdit")
        self.horizontalLayout_3.addWidget(self.primerfileLineEdit)
        self.primerfileButton = QtWidgets.QPushButton(self.layoutWidget9)
        self.primerfileButton.setObjectName("primerfileButton")
        self.horizontalLayout_3.addWidget(self.primerfileButton)
        self.layoutWidget10 = QtWidgets.QWidget(ParameterDlg)
        self.layoutWidget10.setGeometry(QtCore.QRect(17, 12, 240, 23))
        self.layoutWidget10.setObjectName("layoutWidget10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget10)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget10)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.projnameLineEdit = QtWidgets.QLineEdit(self.layoutWidget10)
        self.projnameLineEdit.setObjectName("projnameLineEdit")
        self.horizontalLayout_11.addWidget(self.projnameLineEdit)
        self.label_3.setBuddy(self.uniprimerLineEdit)
        self.label_4.setBuddy(self.barcodelenSpinBox)
        self.label_5.setBuddy(self.mindepthSpinBox)
        self.label_6.setBuddy(self.maxdepthSpinBox)
        self.label_7.setBuddy(self.flankinglengthSpinBox)
        self.muscleLabel.setBuddy(self.muscleLineEdit)
        self.label_2.setBuddy(self.paddingEditLine)
        self.label_8.setBuddy(self.matchscoreSpinBox)
        self.label_9.setBuddy(self.mismatchscireSpinBox)
        self.label_10.setBuddy(self.gapscoreSpinBox)
        self.seqtypeLable.setBuddy(self.fastqRadioBtn)
        self.label.setBuddy(self.phred33RadioBtn)
        self.label_11.setBuddy(self.maxmismatchSpinBox)
        self.label_12.setBuddy(self.threadSpinBox)
        self.inputfileLabel.setBuddy(self.addseqfileButton)
        self.barcodefileLabel.setBuddy(self.barcodefileLineEdit)
        self.outfolderLabel.setBuddy(self.outfolderLineEdit)
        self.primerfileLabel.setBuddy(self.primerfileLineEdit)
        self.label_13.setBuddy(self.projnameLineEdit)

        self.retranslateUi(ParameterDlg)
        self.cancelButton.clicked.connect(ParameterDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(ParameterDlg)
        ParameterDlg.setTabOrder(self.projnameLineEdit, self.addseqfileButton)
        ParameterDlg.setTabOrder(self.addseqfileButton, self.removeseqfileButton)
        ParameterDlg.setTabOrder(self.removeseqfileButton, self.barcodefileButton)
        ParameterDlg.setTabOrder(self.barcodefileButton, self.primerfileButton)
        ParameterDlg.setTabOrder(self.primerfileButton, self.outfolderButton)
        ParameterDlg.setTabOrder(self.outfolderButton, self.okayButton)
        ParameterDlg.setTabOrder(self.okayButton, self.cancelButton)
        ParameterDlg.setTabOrder(self.cancelButton, self.moreButton)
        ParameterDlg.setTabOrder(self.moreButton, self.fastqRadioBtn)
        ParameterDlg.setTabOrder(self.fastqRadioBtn, self.fastaRadioBtn)
        ParameterDlg.setTabOrder(self.fastaRadioBtn, self.phred33RadioBtn)
        ParameterDlg.setTabOrder(self.phred33RadioBtn, self.phred64RadioBtn)
        ParameterDlg.setTabOrder(self.phred64RadioBtn, self.muscleLineEdit)
        ParameterDlg.setTabOrder(self.muscleLineEdit, self.muscleButton)
        ParameterDlg.setTabOrder(self.muscleButton, self.paddingEditLine)
        ParameterDlg.setTabOrder(self.paddingEditLine, self.uniprimerLineEdit)
        ParameterDlg.setTabOrder(self.uniprimerLineEdit, self.barcodelenSpinBox)
        ParameterDlg.setTabOrder(self.barcodelenSpinBox, self.mindepthSpinBox)
        ParameterDlg.setTabOrder(self.mindepthSpinBox, self.maxdepthSpinBox)
        ParameterDlg.setTabOrder(self.maxdepthSpinBox, self.flankinglengthSpinBox)
        ParameterDlg.setTabOrder(self.flankinglengthSpinBox, self.matchscoreSpinBox)
        ParameterDlg.setTabOrder(self.matchscoreSpinBox, self.mismatchscireSpinBox)
        ParameterDlg.setTabOrder(self.mismatchscireSpinBox, self.gapscoreSpinBox)
        ParameterDlg.setTabOrder(self.gapscoreSpinBox, self.maxmismatchSpinBox)
        ParameterDlg.setTabOrder(self.maxmismatchSpinBox, self.threadSpinBox)
        ParameterDlg.setTabOrder(self.threadSpinBox, self.seqfileListWidget)
        ParameterDlg.setTabOrder(self.seqfileListWidget, self.barcodefileLineEdit)
        ParameterDlg.setTabOrder(self.barcodefileLineEdit, self.primerfileLineEdit)
        ParameterDlg.setTabOrder(self.primerfileLineEdit, self.outfolderLineEdit)

    def retranslateUi(self, ParameterDlg):
        _translate = QtCore.QCoreApplication.translate
        ParameterDlg.setWindowTitle(_translate("ParameterDlg", "Project Settings"))
        self.label_3.setText(_translate("ParameterDlg", "Universal Primer:"))
        self.label_4.setText(_translate("ParameterDlg", "Barcode Length:"))
        self.label_5.setText(_translate("ParameterDlg", "Min Read Depth:"))
        self.label_6.setText(_translate("ParameterDlg", "Max Read Depth:"))
        self.label_7.setText(_translate("ParameterDlg", "Flanking Length:"))
        self.muscleLabel.setText(_translate("ParameterDlg", "MUSCLE:"))
        self.muscleButton.setText(_translate("ParameterDlg", "Select"))
        self.label_2.setText(_translate("ParameterDlg", "Padding Sequence:"))
        self.label_8.setText(_translate("ParameterDlg", "Match Score:"))
        self.label_9.setText(_translate("ParameterDlg", "Mismatch Score:"))
        self.label_10.setText(_translate("ParameterDlg", "Gap Score:"))
        self.seqtypeLable.setText(_translate("ParameterDlg", "File Format:"))
        self.fastqRadioBtn.setText(_translate("ParameterDlg", "FASTQ"))
        self.fastaRadioBtn.setText(_translate("ParameterDlg", "FASTA"))
        self.label.setText(_translate("ParameterDlg", "Score Type:"))
        self.phred33RadioBtn.setText(_translate("ParameterDlg", "phred33"))
        self.phred64RadioBtn.setText(_translate("ParameterDlg", "phred64"))
        self.label_11.setText(_translate("ParameterDlg", "Max Mismatch:"))
        self.label_12.setText(_translate("ParameterDlg", "Threads"))
        self.okayButton.setText(_translate("ParameterDlg", "OK"))
        self.cancelButton.setText(_translate("ParameterDlg", "Cancel"))
        self.moreButton.setText(_translate("ParameterDlg", "Advanced >>"))
        self.inputfileLabel.setText(_translate("ParameterDlg", "Sequencing Files:"))
        self.addseqfileButton.setText(_translate("ParameterDlg", "Add File"))
        self.removeseqfileButton.setText(_translate("ParameterDlg", "Remove File"))
        self.barcodefileLabel.setText(_translate("ParameterDlg", "Barcode File:"))
        self.barcodefileButton.setText(_translate("ParameterDlg", "Select"))
        self.outfolderLabel.setText(_translate("ParameterDlg", "Output Folder:"))
        self.outfolderButton.setText(_translate("ParameterDlg", "Select"))
        self.primerfileLabel.setText(_translate("ParameterDlg", "Primer File:"))
        self.primerfileButton.setText(_translate("ParameterDlg", "Select"))
        self.label_13.setText(_translate("ParameterDlg", "Project Name:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ParameterDlg = QtWidgets.QDialog()
    ui = Ui_ParameterDlg()
    ui.setupUi(ParameterDlg)
    ParameterDlg.show()
    sys.exit(app.exec_())

