# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projmergedlg.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProjMergeDlg(object):
    def setupUi(self, ProjMergeDlg):
        ProjMergeDlg.setObjectName("ProjMergeDlg")
        ProjMergeDlg.resize(424, 285)
        self.groupBox = QtWidgets.QGroupBox(ProjMergeDlg)
        self.groupBox.setGeometry(QtCore.QRect(13, 95, 398, 141))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.addButton = QtWidgets.QPushButton(self.groupBox)
        self.addButton.setObjectName("addButton")
        self.gridLayout.addWidget(self.addButton, 0, 1, 1, 1)
        self.removeButton = QtWidgets.QPushButton(self.groupBox)
        self.removeButton.setObjectName("removeButton")
        self.gridLayout.addWidget(self.removeButton, 1, 1, 1, 1)
        self.projsListWidget = QtWidgets.QListWidget(self.groupBox)
        self.projsListWidget.setObjectName("projsListWidget")
        self.gridLayout.addWidget(self.projsListWidget, 0, 0, 3, 1)
        self.layoutWidget = QtWidgets.QWidget(ProjMergeDlg)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 46, 323, 33))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.outfolderEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.outfolderEdit.setObjectName("outfolderEdit")
        self.horizontalLayout.addWidget(self.outfolderEdit)
        self.selectButton = QtWidgets.QPushButton(self.layoutWidget)
        self.selectButton.setObjectName("selectButton")
        self.horizontalLayout.addWidget(self.selectButton)
        self.widget = QtWidgets.QWidget(ProjMergeDlg)
        self.widget.setGeometry(QtCore.QRect(13, 13, 240, 23))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.projnameEdit = QtWidgets.QLineEdit(self.widget)
        self.projnameEdit.setObjectName("projnameEdit")
        self.horizontalLayout_2.addWidget(self.projnameEdit)
        self.widget1 = QtWidgets.QWidget(ProjMergeDlg)
        self.widget1.setGeometry(QtCore.QRect(200, 242, 213, 32))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.cancelButton = QtWidgets.QPushButton(self.widget1)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_3.addWidget(self.cancelButton)
        self.okayButton = QtWidgets.QPushButton(self.widget1)
        self.okayButton.setObjectName("okayButton")
        self.horizontalLayout_3.addWidget(self.okayButton)
        self.layoutWidget.raise_()
        self.groupBox.raise_()
        self.label_2.raise_()
        self.projnameEdit.raise_()
        self.okayButton.raise_()
        self.cancelButton.raise_()
        self.label.setBuddy(self.outfolderEdit)
        self.label_2.setBuddy(self.projnameEdit)

        self.retranslateUi(ProjMergeDlg)
        self.cancelButton.clicked.connect(ProjMergeDlg.reject)
        QtCore.QMetaObject.connectSlotsByName(ProjMergeDlg)
        ProjMergeDlg.setTabOrder(self.projnameEdit, self.outfolderEdit)
        ProjMergeDlg.setTabOrder(self.outfolderEdit, self.selectButton)
        ProjMergeDlg.setTabOrder(self.selectButton, self.addButton)
        ProjMergeDlg.setTabOrder(self.addButton, self.removeButton)
        ProjMergeDlg.setTabOrder(self.removeButton, self.okayButton)
        ProjMergeDlg.setTabOrder(self.okayButton, self.cancelButton)
        ProjMergeDlg.setTabOrder(self.cancelButton, self.projsListWidget)

    def retranslateUi(self, ProjMergeDlg):
        _translate = QtCore.QCoreApplication.translate
        ProjMergeDlg.setWindowTitle(_translate("ProjMergeDlg", "Dialog"))
        self.addButton.setText(_translate("ProjMergeDlg", "Add Project"))
        self.removeButton.setText(_translate("ProjMergeDlg", "Remove"))
        self.label.setText(_translate("ProjMergeDlg", "Project Folder:"))
        self.selectButton.setText(_translate("ProjMergeDlg", "Select"))
        self.label_2.setText(_translate("ProjMergeDlg", "Project Name:"))
        self.cancelButton.setText(_translate("ProjMergeDlg", "Cancel"))
        self.okayButton.setText(_translate("ProjMergeDlg", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProjMergeDlg = QtWidgets.QDialog()
    ui = Ui_ProjMergeDlg()
    ui.setupUi(ProjMergeDlg)
    ProjMergeDlg.show()
    sys.exit(app.exec_())

